<?php include 'header.php';?>

<main id="main" class="mt-5 pt-5">

<!-- ======= Page Header ======= -->
<section class="page-header text-center">
  <div class="container">
    <h1 class="fw-bold">Forensic Ballistics</h1>
    <p class="mb-0">Scientific examination of firearms and ammunition</p>
  </div>
</section>

<!-- ======= Content Section ======= -->
<section class="content-section py-5">
  <div class="container bg-white p-4 rounded shadow-sm">
      
<p>A firearm is any instrument which discharges a missile by the expansive force of the gases produced by burning of an explosive substance. 

</p>
<!-- Due to very large text, content continues exactly as provided -->
<p>Forensic Ballistics is the science dealing with the investigation of firearms, ammunition and problems arising from their use.</p>
<h2>Ballistics</h2>
<p>The term ballistics refers to the science of the travel of a projectile in flight. The flight path of a bullet includes: travel down the barrel, path through the air, and path through a target. The wounding potential of projectiles is a complex matter. (Fackler, 1996)</p>
<h2>Anatomy of Firearms</h2>
<p>General make-up and Mechanism: Firearms consist of a metal barrel in the form of hollow cylinder of varying length, which is closed at the back end and is called the breech end; and the front open end is called the muzzle end. The inside of the barrel consists of three parts. (1) The chamber, at the breech end to accommodate the cartridge, which is usually of large size than the bore, (2) the taper, called lead or leed in rifled arm and chamber cone in a smooth bore, connects the chamber to the bore, and (3) the bore, which lies between the taper and the muzzle. A breech action is attached to the barrel at the breech end to close the end of the barrel. It consists of a receiver which contains a bolt or block which closes and locks. The bolt or the block can be opened to insert a fresh cartridge into the chamber. When the weapon is closed for firing, the barrel comes into position against a flat block of metal called breech face, which seals the breech end of the chamber. The block is pierced in its centre to accommodate the firing pin which is actuated by a spring and moves forward when trigger is pressed. When the weapon the weapon is cocked (ready to be fired), the hammer has been pulled back against a strong spring and is held back by the end of the sear, which rests in a notch known as the bent. When the trigger is pulled, the sear is disengaged from the bent and the hammer moves forward and strikes a small pushrod (firing pin or striker). Occasionally, the firing pin and hammer are external and can be pulled aback of the bolt action. The barrel of a “breakdown” action gun or rifle, i.e., a weapon which opens like a shotgun, has at its breech end a moveable limb called extractor, which moves backwards withdrawing the cartridge, when the breech is opened. In a bolt action weapon, a small claw fitted to the front end of the bolt, pulls out the cartridge with it, when the bolt is withdrawn. The lock contains the lock and trigger mechanism, i.e., the apparatus for discharge of the weapon. A firearm s provided with sights with which one can aim, so that the bullet can strike the target accurately. The ‘stock’ is the supporting or handle part of the weapon, the end of which is the ‘butt’. Usually the trigger mechanism and any provision for reloading and ejecting cartridges is within the stock. The hand –arms are provided with grips for grasping them by hand. In long barreled weapons, the butt is elongated to fit into shoulder. Those with long barrels are fired from the shoulder, i.e., rifle and shotgun, and those with short barrels may be fired from the hand, i.e., pistol and revolver. Firearms except revolves and hammer guns have a safety device, which locks the firing mechanism when it is applied, known as safety catch.</p>
<h2>Classification</h2>
<p>: (I) Rifled weapons: (1) Rifles: (a) Air and gas-operated rifles. (b) 0.22 rifles. (c) Military and sporting rifles. (2) Single-shot target-practice pistols. (3) Revolvers. (4) Automatic pistols. (5) True automatic weapons (machine guns). 
(II) Smooth-bored weapons (shotgun). (1) Single barrel. (2) Double barrel. (3) Slide-action. (4) Bolt-action. (5) Semi-automatic. (6) Automatic.
</p>
<h2>Handguns</h2>
<p>From the very start, a handgun was conceived as a compact weapon for self defense. Even though today there are handguns made specifically for target competition or hunting, most are still designed with defense in mind. Thus, handguns are compact for concealability and ease of carrying. This becomes a part of the legal definition of a handgun, as they are considered "concealable" and therefore deemed dangerous and are controlled by law in most states. Of course, a handgun should be capable of firing a projectile accurately at a target. The energy delivered must be sufficient to quell any attack, yet be light enough so that the recoil generated does not wrest the gun from the shooter's hand; this is difficult in practice and there is no perfect choice, so many types of handguns are manufactured for different situations. Finally, since no one can be guaranteed a perfect shot or a single attacker, a handgun must fire multiple shots. The two most common defensive handguns are the double action revolver and the semiautomatic pistol.</p>
<h3>Revolver</h3>
<p>The revolver has several advantages and unique features. Importantly, they are less expensive, simpler in design, and more reliable than semiautomatics. A revolver is easy to master, even for novices. Revolvers, for whatever reason, seem to be more accurate than semiautomatics. On the bad side, revolvers are limited to six shots, are relatively slow to reload, the gap between barrel and cylinder makes them less efficient, and the trigger pull is greater. The anatomy of a representative double action revolver is shown below:
 
Barrel length is smaller for concealability and longer for accuracy or energy. The ejector rod under the barrel is used to eject fired cartridges before reloading. Sights on a revolver are usually a blade in the front and a notch on the rear. The frame is the largest part, and all other pieces attach to it. Frames are usually made of blued or plated steel, stainless steel, or lightweight alloys. A revolver may weigh less than 1 lb to more than 4 lbs. The cylinder contains five or six holes for the cartridges and can be swung out for easy reloading. This must be a conscious act, so that no empty cartridge cases will be found at a crime scene unless the assailant stopped to reload.
There is a gap between cylinder and barrel to allow the cylinder to turn freely, but this also allows gases to escape laterally, which at close range may deposit gunshot residue on surrounding structures and allow the forensic pathologist to reconstruct the scene. The lockwork translates the trigger pull to rotation of the cylinder, cocking and fall of the hammer. If this is done in one motion of pulling the trigger, it is termed "double-action." Single-action revolvers (old Colts of "cowboys") require manual cocking of the hammer before the trigger is pulled. Different types of grips are employed; larger grips allow more accuracy, smaller grips provide.
</p>
<h3>Semiautomatic Pistol</h3>
<p>This is a more recent development than the revolver, originating late in the 19th century, mostly through the efforts of John Browning. In fact, almost every semiautomatic handgun available today is a copy of his two most famous designs: the Colt model 1911A government 45 and the Browning Hi Power 9 mm. The anatomy of a semiautomatic pistol is given below:
 
The advantage of semiautomatics is the use of recoil generated by the fired cartridge to eject the empty cartridge case, load the next cartridge, and cock the hammer. This is more conducive to firing multiple shots, so many are designed to carry 15 to 19 rounds. Disadvantages include a more complicated mechanism, require more practice to use, and cartridge cases must be short to work well. Revolver cartridges are more powerful than semiautomatic cartridges for this last reason.
The barrel is normally hidden by the slide. Choices of barrel length are limited. The slide is a key part to the operation of a semiautomatic:
 
The slide is able to move back along the axis of the barrel under tension from a spring. Since the cartridge base rests on the slide, the slide does just that under the force of recoil generated by the firing of the cartridge. As the slide and empty cartridge case are accelerating backwards, the case is struck by a stationary piece of metal that bumps it to the side. This is conveniently located next to a hole in the slide, so that the empty cartridge case continues its acceleration in a direction perpendicular to the pistol and into the air, landing from 2 to 20 feet from the fired gun. The rearward- moving slide also cocks the hammer. After the case is clear the slide hits a stop and the spring tension starts it forward. The magazine spring is pushing on a column of rounds tight up against the bottom of the slide. As the slide comes back by the column of cartridges, it grabs the top one and pushes it forward and up a short ramp into the chamber where the slide locks it in place.
The handle, or butt, is more important here because it contains the magazine holding the cartridges. Safety mechanisms prevent accidental firing. Some lock the hammer, while other designs lock the trigger.
Even on open ground ejected cases may be difficult to find, as they typically roll into a hiding place such as grass or small depressions in the ground. Thus, ejected cases will virtually always be left behind at the scene, but must be searched for diligently.
</p>
<h2>Rifles</h2>
<p>Rifles differ from handguns in the length of the barrel and the presence of a butt stock. They are harder to carry, are poorly concealable, and more loosely regulated than handguns. However, they are much more accurate and shoot more powerful cartridges than handguns. Rifles may be manufactured as single shot, but most commonly are bolt action, used for large caliber hunting rifles. Military rifles are seimiautomatic or automatic, having a detachable magazine holding 5 to 50 rounds. Pump action and lever action rifles, usually of lower caliber, have magazines below the barrel.</p>
<h2>Shotguns</h2>
<p>Shotguns have a similar external appearance to rifles, but differ in the lack of rifling inside the barrel, which is the basis for their legal definition. A shotgun shell may contain one large projectile (called a slug), a few pellets of large shot, or many tiny pellets. Shotguns are available in single shot (break action), double barrel, pump action, and semiautomatic.</p>
<h2>Other Types of Firearms</h2>
<p>The single action revolver has remained popular for its historic appeal, reliable design, and uncanny balance. For some reason a single action Colt 45 is easier to shoot from the hip than a modern revolver, and is used almost exclusively in trick shooting.
Semiautomatic versions of submachine guns (such as the Uzi) are classed as pistols for legal reasons. These often have the ability to hold 20 to 30 rounds, but are otherwise identical to conventional handguns in similar caliber. The expense of such weapons precludes their use by most criminals, but they may be used by persons involved in organized crime, drug-dealing, and gangs.
Air guns which use pneumatic pressure to fire a projectile are generally known as "BB guns" and have been around for over 200 years. Three mechanisms are employed:
1.	Air is pumped into a pressure chamber reservoir and released by trigger pull 
2.	A spring compression system is used to drive a piston to compress air (most "toys" are of this variety) 
3.	A pressurized, carbon dioxide filled cartridge is attached. (Harris et al, 1983)
Even though cheap "Saturday night specials" are readily available, youths and youth gang members may attempt to build their own firearms. Typically, they are crude, and adapted to fire available ammunition. In one study, such guns caused unusual muzzle imprints, intensive soot deposits at the entrance wounds and on the hands, intensive CO-effects, burns, and in one case a skin laceration of the hand holding the weapon. The bullets showed a reduced penetration depth, and characteristic firing marks were missing. (Karger et al, 1995)
Lastly, there has arisen a new group of handguns for hunting big game and long range target competition that are nothing but single shot rifles with shortened barrels and no buttstock. These shoot rifle or hybrid rifle cartridges and deliver rifle energies.
</p>
<h2>Cartridge, Primers, Powders, Bullets</h2>
<p>What can be learned from specific cartridge data? If the 44 magnum is compared with the 357 magnum, the effect of bore diameter is seen. The larger area of the 44 magnum creates more force with the same pressure, allowing the 44 magnum  to produce more energy at the muzzle. The effect of case capacity can be demonstrated in a comparison of the 9 mm parabellum (para) with the 357 magnum. These cartridges have similar diameters and pressures, but the 357 magnum is much longer, yielding more case volume (more powder), and delivers more energy. Finally, despite the Colt 45 having the largest bore diameter and one of the longest cases, it does not deliver the maximum energy because the outdated 1873 design of this cartridge case severely handicaps its pressure handling capability.
The Glasser "safety slug" has been designed to consist of a hollow copper jacket filled with #12 birdshot. It has been designed in several calibers. When the bullet hits the target, the pellets are released over a wide area. However, the pellets quickly decelerate over a short distance, so they may penetrate poorly and are less likely to hit surrounding targets. They are designed to stop, but not kill, an attacker while avoiding injury to bystanders. At close range, they may produce substantial injury.
The Winchester "Black Talon" cartridge, which comes in several calibers, is designed with a lead core locked to a copper alloy jacket by a unique notching process that is done to prevent separation of teh core and the jacket on target impact via controlled expansion. This expansion is desinged to occur in a delayed fashion at the muzzle velocities of the bullet in order to provide deeper penetration. In addition, the jacket is thicker at the tip than at the heel, with precutting of the thick portion to that, upon target impact, six sharp copper points are raised in a radial fashion. The purpose of this design is to increase expansion and cavitation with greater transference of energy. In one study with test firings, black talons penetrating plastic sheeting (simulating elasticity of skin) expanded irregularly, while those fired into ordnance gelatin (simulating soft tissue) uniformly expanded. The copper points create a potential hazard in bullet removal by surgeons or forensic scientists. (Russel et al, 1995)
"Shotshell" cartridges containing pellets are available in a variety of calibers. In a study by Speak et al (1985), it was found that, in handguns, either shorter barrel length or larger caliber produced larger pellet patterns.
Armour-piercing bullets are designed to penetrate soft body armor (such as bulletproof vests worn by law enforcement officers). Though they penetrate such armor, they produce no more wounding than ordinary bullets of similar size. Some have teflon coatings to minimize barrel wear with firing. They may demonstrate less deformation when recovered. They are illegal to possess and use.
Diagrammatic representations of standard handgun and rifle cartridges are shown below. The metal casing encloses the powder, above which the bullet is seated. The powder is ignited through the flash hole when the primer is struck. A case with a rim is found with revolver and lever action rifle cartridges, and also with some some bolt action and semi-automatic rifles.
 
Shotgun Ballistics
Wounding is a function of the type of shot, or pellets, used in the shotgun shell. Weight, in general, is a constant for a shell so that 1 oz of shot would equal either 9 pellets of double O buckshot or 410 pellets of #8 birdshot. A 00 or "double ought" pellet is essentially equivalent to a low velocity .38 handgun projectile. The spread of the pellets as they leave the muzzle is determined by the "choke" or constriction of the barrel at the muzzle (from 0.003 to 0.04 inches). More choke means less spread. Full choke gives a 15 inch spread at 20 yards, while no choke gives a 30 inch spread at the same distance. (DeMuth et al, 1976) A "sawed-off" shotgun has a very short barrel so that, not only can it be concealed more easily, but also it can spray the pellets out over a wide area, because there is no choke.
A shotgun shell is diagrammed below:
 
Cartridge: It consists of a metal cylinder with a flat base which projects as a rim except in an automatic pistol. Rimless cartridge has an extractor groove near the base. The primer cup (percussion cup) is fitted in a circular hole, usually in the centre of the base and has a flash hole in the centre which communicates with the powder space inside. The metal cylinder or cartridge case is elongated, and its distal end tightly grips the base of the bullet. The gunpowder lies between the detonator and the bullet. Usually there is no wad, but sometimes one piece wad is kept. Low-power rim-fire cartridge may not contain gunpowder but only a primer compound in a hollow rim. As such, those cartridges cannot produce the tattooing. Many bullets have near the base, a circumferential groove called “cannelure”, into which the end of the case is crimped. A bullet without cannelure is held in position by stabs on the circumference of the case.
	Primers: Primers are ignited by impact (percussion) of the gun’s firing pin. Centrefire rifle and pistol primers are small metal cups usually held in place in the cartridge head primer pocket by friction. The primer cup contains the priming mixture and an anvil so placed that the blow of firing pin on the primer cup crushes the priming mixture against the anvil centre and burns it, which then flashes through the flash hole (fire holes or vents) in the centrefire case head, and ignites the powder charge. The primer used in shotgun cartridge is called a primer battery cup. This consists of a battery cup into which a primer cup fits. The battery cup supports the anvil and provides a flash hole. It is also held in place by friction. The priming mixture contains lead peroxide, lead styphnate, tetrazene, barium nitrate, etc. In rimfire cartridges no percussion sup is provided. The priming mixture is contained within the hollow rim of the cartridge and ignited when it is crushed between the rim walls of the cartridge head b the impact of the firing pin.
	Powders: 
(1)	Black Powder: It consists of potassium nitrate 75%; sulplure 10%; and charcoal 15%. It is designated as FG, FFG, FFFG, etc., depending on the size of the grains. The more number of Fs, the finer are the grains and the faster in burning. The powder grains are black, coarse or fine, without any particular shape. It burns with production of much heat, flame and smoke. Fine grains travel 60 to 90 cm. or more. One gram of powder produces 3,000 to 4,500 c.c. of gas. The gas consists of CO, CO2, nitrogen, hydrogen sulphide, hydrogen, methane, etc., all at a very high temperature.
(2)	Smokeless Powders: It consists of nitrocellulose (gun cotton), or nitroglycerine and nitrocellulose (double-base). They produce much less flame and smoke and are more completely burnt than black powder. One gram produces 12,000 to 13,000 c.c. of gases. The colour varies from bright organe to bluish-black, and in shape from minute globules, flakes, square, rectangular, irregular discs, cylinders to longer threads. Semi-smokeless powder is a mixture of 80% of black and 20% of the smokeless type.
Bullets: The traditional bullet is made of soft metal and has a rounded nose. The metal is lead with varying anmounts of antimony added to provide hardness. This is known as the round-nose soft bullet, and is usually used in rifles and revolvers. The caliber of a bullet is its cross-sectional diameter. in revolver and pistol,  the bullet is short and the point usually round or ogival. In rifle, the bullet is elongated with pointed end. Variations are: (1) Square-nosed, soft metal bullet, known as “wad-cutter”, and used primarily for target shooting. (2) Hollow-point variety has a depression in the nose of the soft metal. This bullet is designed to expand or “mushroom’ upon impact.
	Jacketed bullets are of two types: (1) The full metal jacket bullet in which a tough, heavy jacket covers all but the base, where the soft metal interior is exposed. The tough jacket may be made of steel, copper, nickel and zinc. (2) The semi-jacketed bullet is provided with a relatively thin but tough jacket, which covers the base and the cylindrical portion of the bullet, leaving the nose partly or fully exposed. This type is designed to expand or “mushroom” like the soft metal, hollow-point type. The combination of the above two is also available. Mushroom bullets produce more serious wounds. Other types of bullets are (1) Short flat-point. (2) Medium flat-point. (3) Medium round-nose. (4) Long round-nose. (5) Medium long sharp-point. (6) Medium sharp-point. (7) Flat base. (8) Sharp-point boat-tailed. (9) Pencil-point. (10) Streamlined with sabot.
	The flat base is the most common. In boat-tail bases, the base tapers to the flat with a profile, much like the rear portion of a boat. Rifle bullet weights range from 2 to 33 grams. A dumdum bullet is open at the base, and has the point covered with the jacket. When it strikes an object, the lead at the point expands or mushrooms, and produces a large hole. Expanding dumdum bullets, where the tip of the jacket is cut off, fragment extensively upon striking, and produce extensive wounds with ragged margins. A bullet with a hole in the point is called hollow-point or ‘express bullet. Incendiary bullets contain phosphorus.
	Explosive Bullets: The exploding bullet is of various types. The common type has a cylinder  inserted into the tip of the bullet. The cylinder contains either black powder or a detonator, such as lead azide. The cavity may contain a single lead shot and possibly a percussion cap and a tiny primer anvil. The wound produced is larger than the usual. If the missile explodes. There is greater fragmentation of the bullet and increased destruction of the tissues. The surgeon and pathologist should wear goggles and use long-handled instruments to manipulate the missile during surgical operation or autopsy, as they are vulnerable to detonations of explosive missiles. The removed bullet should be handled with long rubber-covered forceps and kept in a padded container to protect it from excess impact, vibration and heat.
	Plastic bullets: Buton round (plastic bullet) is a solid cylinder of polyvinyl chloride (PVC), 38 mm. in diameter, 10 cm. long, weighing 135 g. It is fired from a smooth-bore weapon and is effective up to 50 to 70 metres. They are used for riot control. It should not be fired at a person under 20 metres range. It causes bruising and pain. Fracture of the skull, eye damage, fracture of ribs, limb bones, and contusions of liver, lung and spleen have been reported.
	Mechanism of Discharge of Projectile: A firearm is fired when the trigger is pulled, which is usually situated below, or below and behind the breech. The trigger releases a pin or hammer, whose tip strikes the percussion cap at the base of the cartridge, which explodes by heat created by the strike of the firing pin and sends a flash through a tiny hole into the main body of the powder-filled case, which sets fire to the powder charge or propellent, producing instantaneously a large amount of gas which is under high pressure. The cartridge case swells outwards, due to which the hold on the bullet is released, and forces the bullet into the barrel. Simultaneously, the cartridge case is pushed backwards with equal force against the breech face. The bullet passes out. The confined gas behind it gives recoil thrust to the gun. Noise of gun firing is caused by muzzle blast, or due to the suddenly released gases disturbing the air. If the velocity of the bullet is more than the speed of sound, then there is also a crack from that. The bullet reaches its maximum velocity as it comes out at the open end of the barrel and this is called muzzle velocity. The bullet is followed by a blast of highly compressed hot gas, particles of partially burnt and unburnt powder, smoke, flame and fragments of metal, cartridge and detonator, grease and wad or disc matter. The blast has the shape of a cone whose apex is located at the muzzle. All these things produce some effect on the body at short ranges.
	Mechanics of Bullet Wound Production: 
(1)	Bullet Velocity: A bullet’s ability to wound is directly related to its kinetic energy (E=mv2/2) at the moment of impact. Because kinetic energy increases in direct proportion to weight (mass) of the missile and the square of its velocity, a bullet traveling at twice the speed of a second bullet of equal weight and similar shape, possesses four times much energy or wounding power. Tissue damage produced by high velocity a bullet is disproportionately greater than that produced by bullet of ordinary muzzle velocity. A wound produced by a bullet, whose impact speed equals its muzzle velocity is more severe, than that produced by the same bullet, discharged from the same gun, whose speed has been reduced due to traveling a long distance before it strikes it s target.
(2)	Tissue Density: The greater the tissue density, the greater is the amount of energy discharged by the bullet’s passing through it. A bullet may cause slight damage to the soft tissues, but the same bullet at the same speed can produce extensive comminution of the bone.
(3)	Hydrostalic Forces: Hydrostatic forces cause excessive degree of destruction. When a bullet passes through a fluid-distended hollow organ, e.g., food-filled stomach, urine-filled bladder, CSF-filled ventricles of the brain, or a heart chamber distended with blood in diastole, produces extensive lacerations due to the explosive displacement of the liquid in all directions. 




</p>
<h2>Mechanism of Discharge</h2>
<p>What can be learned from specific cartridge data? If the 44 magnum is compared with the 357 magnum, the effect of bore diameter is seen. The larger area of the 44 magnum creates more force with the same pressure, allowing the 44 magnum  to produce more energy at the muzzle. The effect of case capacity can be demonstrated in a comparison of the 9 mm parabellum (para) with the 357 magnum. These cartridges have similar diameters and pressures, but the 357 magnum is much longer, yielding more case volume (more powder), and delivers more energy. Finally, despite the Colt 45 having the largest bore diameter and one of the longest cases, it does not deliver the maximum energy because the outdated 1873 design of this cartridge case severely handicaps its pressure handling capability.
The Glasser "safety slug" has been designed to consist of a hollow copper jacket filled with #12 birdshot. It has been designed in several calibers. When the bullet hits the target, the pellets are released over a wide area. However, the pellets quickly decelerate over a short distance, so they may penetrate poorly and are less likely to hit surrounding targets. They are designed to stop, but not kill, an attacker while avoiding injury to bystanders. At close range, they may produce substantial injury.
The Winchester "Black Talon" cartridge, which comes in several calibers, is designed with a lead core locked to a copper alloy jacket by a unique notching process that is done to prevent separation of teh core and the jacket on target impact via controlled expansion. This expansion is desinged to occur in a delayed fashion at the muzzle velocities of the bullet in order to provide deeper penetration. In addition, the jacket is thicker at the tip than at the heel, with precutting of the thick portion to that, upon target impact, six sharp copper points are raised in a radial fashion. The purpose of this design is to increase expansion and cavitation with greater transference of energy. In one study with test firings, black talons penetrating plastic sheeting (simulating elasticity of skin) expanded irregularly, while those fired into ordnance gelatin (simulating soft tissue) uniformly expanded. The copper points create a potential hazard in bullet removal by surgeons or forensic scientists. (Russel et al, 1995)
"Shotshell" cartridges containing pellets are available in a variety of calibers. In a study by Speak et al (1985), it was found that, in handguns, either shorter barrel length or larger caliber produced larger pellet patterns.
Armour-piercing bullets are designed to penetrate soft body armor (such as bulletproof vests worn by law enforcement officers). Though they penetrate such armor, they produce no more wounding than ordinary bullets of similar size. Some have teflon coatings to minimize barrel wear with firing. They may demonstrate less deformation when recovered. They are illegal to possess and use.
Diagrammatic representations of standard handgun and rifle cartridges are shown below. The metal casing encloses the powder, above which the bullet is seated. The powder is ignited through the flash hole when the primer is struck. A case with a rim is found with revolver and lever action rifle cartridges, and also with some some bolt action and semi-automatic rifles.
 
Shotgun Ballistics
Wounding is a function of the type of shot, or pellets, used in the shotgun shell. Weight, in general, is a constant for a shell so that 1 oz of shot would equal either 9 pellets of double O buckshot or 410 pellets of #8 birdshot. A 00 or "double ought" pellet is essentially equivalent to a low velocity .38 handgun projectile. The spread of the pellets as they leave the muzzle is determined by the "choke" or constriction of the barrel at the muzzle (from 0.003 to 0.04 inches). More choke means less spread. Full choke gives a 15 inch spread at 20 yards, while no choke gives a 30 inch spread at the same distance. (DeMuth et al, 1976) A "sawed-off" shotgun has a very short barrel so that, not only can it be concealed more easily, but also it can spray the pellets out over a wide area, because there is no choke.
A shotgun shell is diagrammed below:
 
Cartridge: It consists of a metal cylinder with a flat base which projects as a rim except in an automatic pistol. Rimless cartridge has an extractor groove near the base. The primer cup (percussion cup) is fitted in a circular hole, usually in the centre of the base and has a flash hole in the centre which communicates with the powder space inside. The metal cylinder or cartridge case is elongated, and its distal end tightly grips the base of the bullet. The gunpowder lies between the detonator and the bullet. Usually there is no wad, but sometimes one piece wad is kept. Low-power rim-fire cartridge may not contain gunpowder but only a primer compound in a hollow rim. As such, those cartridges cannot produce the tattooing. Many bullets have near the base, a circumferential groove called “cannelure”, into which the end of the case is crimped. A bullet without cannelure is held in position by stabs on the circumference of the case.
	Primers: Primers are ignited by impact (percussion) of the gun’s firing pin. Centrefire rifle and pistol primers are small metal cups usually held in place in the cartridge head primer pocket by friction. The primer cup contains the priming mixture and an anvil so placed that the blow of firing pin on the primer cup crushes the priming mixture against the anvil centre and burns it, which then flashes through the flash hole (fire holes or vents) in the centrefire case head, and ignites the powder charge. The primer used in shotgun cartridge is called a primer battery cup. This consists of a battery cup into which a primer cup fits. The battery cup supports the anvil and provides a flash hole. It is also held in place by friction. The priming mixture contains lead peroxide, lead styphnate, tetrazene, barium nitrate, etc. In rimfire cartridges no percussion sup is provided. The priming mixture is contained within the hollow rim of the cartridge and ignited when it is crushed between the rim walls of the cartridge head b the impact of the firing pin.
	Powders: 
(1)	Black Powder: It consists of potassium nitrate 75%; sulplure 10%; and charcoal 15%. It is designated as FG, FFG, FFFG, etc., depending on the size of the grains. The more number of Fs, the finer are the grains and the faster in burning. The powder grains are black, coarse or fine, without any particular shape. It burns with production of much heat, flame and smoke. Fine grains travel 60 to 90 cm. or more. One gram of powder produces 3,000 to 4,500 c.c. of gas. The gas consists of CO, CO2, nitrogen, hydrogen sulphide, hydrogen, methane, etc., all at a very high temperature.
(2)	Smokeless Powders: It consists of nitrocellulose (gun cotton), or nitroglycerine and nitrocellulose (double-base). They produce much less flame and smoke and are more completely burnt than black powder. One gram produces 12,000 to 13,000 c.c. of gases. The colour varies from bright organe to bluish-black, and in shape from minute globules, flakes, square, rectangular, irregular discs, cylinders to longer threads. Semi-smokeless powder is a mixture of 80% of black and 20% of the smokeless type.
Bullets: The traditional bullet is made of soft metal and has a rounded nose. The metal is lead with varying anmounts of antimony added to provide hardness. This is known as the round-nose soft bullet, and is usually used in rifles and revolvers. The caliber of a bullet is its cross-sectional diameter. in revolver and pistol,  the bullet is short and the point usually round or ogival. In rifle, the bullet is elongated with pointed end. Variations are: (1) Square-nosed, soft metal bullet, known as “wad-cutter”, and used primarily for target shooting. (2) Hollow-point variety has a depression in the nose of the soft metal. This bullet is designed to expand or “mushroom’ upon impact.
	Jacketed bullets are of two types: (1) The full metal jacket bullet in which a tough, heavy jacket covers all but the base, where the soft metal interior is exposed. The tough jacket may be made of steel, copper, nickel and zinc. (2) The semi-jacketed bullet is provided with a relatively thin but tough jacket, which covers the base and the cylindrical portion of the bullet, leaving the nose partly or fully exposed. This type is designed to expand or “mushroom” like the soft metal, hollow-point type. The combination of the above two is also available. Mushroom bullets produce more serious wounds. Other types of bullets are (1) Short flat-point. (2) Medium flat-point. (3) Medium round-nose. (4) Long round-nose. (5) Medium long sharp-point. (6) Medium sharp-point. (7) Flat base. (8) Sharp-point boat-tailed. (9) Pencil-point. (10) Streamlined with sabot.
	The flat base is the most common. In boat-tail bases, the base tapers to the flat with a profile, much like the rear portion of a boat. Rifle bullet weights range from 2 to 33 grams. A dumdum bullet is open at the base, and has the point covered with the jacket. When it strikes an object, the lead at the point expands or mushrooms, and produces a large hole. Expanding dumdum bullets, where the tip of the jacket is cut off, fragment extensively upon striking, and produce extensive wounds with ragged margins. A bullet with a hole in the point is called hollow-point or ‘express bullet. Incendiary bullets contain phosphorus.
	Explosive Bullets: The exploding bullet is of various types. The common type has a cylinder  inserted into the tip of the bullet. The cylinder contains either black powder or a detonator, such as lead azide. The cavity may contain a single lead shot and possibly a percussion cap and a tiny primer anvil. The wound produced is larger than the usual. If the missile explodes. There is greater fragmentation of the bullet and increased destruction of the tissues. The surgeon and pathologist should wear goggles and use long-handled instruments to manipulate the missile during surgical operation or autopsy, as they are vulnerable to detonations of explosive missiles. The removed bullet should be handled with long rubber-covered forceps and kept in a padded container to protect it from excess impact, vibration and heat.
	Plastic bullets: Buton round (plastic bullet) is a solid cylinder of polyvinyl chloride (PVC), 38 mm. in diameter, 10 cm. long, weighing 135 g. It is fired from a smooth-bore weapon and is effective up to 50 to 70 metres. They are used for riot control. It should not be fired at a person under 20 metres range. It causes bruising and pain. Fracture of the skull, eye damage, fracture of ribs, limb bones, and contusions of liver, lung and spleen have been reported.
	Mechanism of Discharge of Projectile: A firearm is fired when the trigger is pulled, which is usually situated below, or below and behind the breech. The trigger releases a pin or hammer, whose tip strikes the percussion cap at the base of the cartridge, which explodes by heat created by the strike of the firing pin and sends a flash through a tiny hole into the main body of the powder-filled case, which sets fire to the powder charge or propellent, producing instantaneously a large amount of gas which is under high pressure. The cartridge case swells outwards, due to which the hold on the bullet is released, and forces the bullet into the barrel. Simultaneously, the cartridge case is pushed backwards with equal force against the breech face. The bullet passes out. The confined gas behind it gives recoil thrust to the gun. Noise of gun firing is caused by muzzle blast, or due to the suddenly released gases disturbing the air. If the velocity of the bullet is more than the speed of sound, then there is also a crack from that. The bullet reaches its maximum velocity as it comes out at the open end of the barrel and this is called muzzle velocity. The bullet is followed by a blast of highly compressed hot gas, particles of partially burnt and unburnt powder, smoke, flame and fragments of metal, cartridge and detonator, grease and wad or disc matter. The blast has the shape of a cone whose apex is located at the muzzle. All these things produce some effect on the body at short ranges.
	Mechanics of Bullet Wound Production: 
(1)	Bullet Velocity: A bullet’s ability to wound is directly related to its kinetic energy (E=mv2/2) at the moment of impact. Because kinetic energy increases in direct proportion to weight (mass) of the missile and the square of its velocity, a bullet traveling at twice the speed of a second bullet of equal weight and similar shape, possesses four times much energy or wounding power. Tissue damage produced by high velocity a bullet is disproportionately greater than that produced by bullet of ordinary muzzle velocity. A wound produced by a bullet, whose impact speed equals its muzzle velocity is more severe, than that produced by the same bullet, discharged from the same gun, whose speed has been reduced due to traveling a long distance before it strikes it s target.
(2)	Tissue Density: The greater the tissue density, the greater is the amount of energy discharged by the bullet’s passing through it. A bullet may cause slight damage to the soft tissues, but the same bullet at the same speed can produce extensive comminution of the bone.
(3)	Hydrostalic Forces: Hydrostatic forces cause excessive degree of destruction. When a bullet passes through a fluid-distended hollow organ, e.g., food-filled stomach, urine-filled bladder, CSF-filled ventricles of the brain, or a heart chamber distended with blood in diastole, produces extensive lacerations due to the explosive displacement of the liquid in all directions. 



</p>

<h2>Criminalistics Laboratory Methods</h2>
<p>Surgical pathology description of bullets
Each bullet keeps a diary in its own way of where it has been and what it has done. Now that you understand the function of a bullet, many of these changes become easy to interpret. The bullet base will contain irregular dimples marking the pressure delivered there in its acceleration. the bullet sides will bear the markings of the barrel interior rifling. These spiral lines, or striae, contain the micrscopic imperfections of the gun from which it was fired and can be as specific as a fingerprint. The bullet nose carries information about the target, and recognizing these may give a clue to the injury rendered.
Remember in measuring bullets to determine the type of cartridge used that the actual bullet diameter, even of non-deformed bullets, is not the same as the name of the cartridge. Most names have a historic basis and have little to do with any real physical measurements: a .30-06 was named for a .30 caliber cartridge developed in 1906; the handgun cartridges called .357 magnum, .38 special, and 9 mm parabellum have essentially the same .357 inch actual diameter. Therefore, use caution in opinions regarding the type of weapon or cartridge used based upon examination of bullets.
The best surgical pathology description would give dimensions as measured (use vernier calipers for best results), shape, and appearance of surface. Photography will be valuable.
Expansion of a semi-wadcutter hollowpoint bullet increases the frontal area and blunts the shape. The degree to which this happens depends upon the texture of the tissue impacted, the velocity at impact, and the softness of the bullet (usually quite constant). With the exceptions of lung and bone, tissue densities are relatively constant. Velocity is the most important factor.
No change in shape occurs until impact velocity achieves about 800 fps. Between 800 and 1000 fps a slight flattening of the bullet nose can be expected. Over 1000 fps real expansion starts to occur and by 1200 fps the nose is turned over to form a mushroom shape. An interesting artefact of impacts around 1000 fps is the tendency of the copper jacket to be shed from the lead. The jacket stops in the subcutaneous tissue and the bullet will continue to penetrate. This accounts for fragments of copper (with rifling marks) commonly seen as surgical specimens. At velocities approaching 1500 fps the bullet is transformed into a rounded ball of lead and copper. The above results are uniformly valid only in artificial media (such as ordnance gelatin) but correlate with human tissue. Examples follow on the next page:
The soft exposed lead nose on non-full metal jacketed bullets can be imprinted with anything that is penetrated by the bullet. Wood, glass, fabric, plastic, or tissue may leave marks as well as fragments on the bullet tip. Bone struck by bullets may not only fragment the bone, but also split the bullet. Lead round nose bullets can penetrate deeply and strike bone at relatively high velocity and can be cleanly cut in half or shaved vertically. Full metal jacketed round nose bullets are less affected, but are often irregularly flattened upon striking bone. Bullets that come to rest in soft tissue without striking bone are often intact.
Intermediate targets, such as glass, wood, clothing, or even paper, may influence the path, shape, and fragmentation of projectiles. Such factors must be taken into account in the recovery of evidence. (Stahl et al, 1979) Even tempered glass, which shatters and fragments easily on impact, may deflect handgun bullets (low velocity) significantly. High velocity, jacketed bullets will be deflected much less. (Thornton, 1986)
Flattening of shotgun pellets may not necessarily indicate a close range contact with a target, as the pellets may be deformed on firing. Recently developed shells use plastic packing materials and plastic capping to diminish deformation. (DeMuth et al, 1978)
Even pellets of air guns may show characteristic striae (Cohle et al, 1987). Silencers used over the muzzle of a gun are often misaligned and can produce characteristic striae. (Menzies et al, 1981)
</p>
<h2>Examination of Bullets</h2>
<p>If a bullet is recovered from the scene or from the body, it may be compared to bullets obtained by test-firing the suspected weapon. Test firing is done using similar ammunition. Bullets are marked on the nose at the 12 o'clock barrel position (called "index", "witness", or "reference" marks). Consecutive test bullets are then fired into a water tank, recovered, and juxtaposed with a comparison microscope to compare test bullets with the recovered evidence. Index marks help to align test bullets to determine reproducibility of markings. Photographs should be taken (a ruler or coin can be used to give scale and alignment).
Comparison of bullets involves "class" and "individual" characteristics. These characteristics are based upon "striae" left on the bullet as it passes through the barrel.
Class refers to the type of caliber and rifling. Rifling pattern may turn to the right or left, with a given rate of twist. The number and depth of grooves can vary also. Some newer guns use "polygonal" rifling resembling the reversed image of a twisted square rod. A particular type of gun (.38 Smith and Wesson, or 9 mm Glock) will impart these class characteristics.
Individual characteristics are used to try and determine if a specific gun (say one of many 9 mm Glocks) was used. These individual characteristics are based upon burrs or imperfections in the barrel, particularly the muzzle, that impart specific markings, or striae, to fired bullets. If such markings are present, they may lead to a "determinative" identification. In general, smaller caliber weapons (.22) yield fewer reproducible characteristics in fired bullets than weapons of larger caliber (.45).
In the image below, two sets of bullets of the same class are roughly compared to indicate how difficult this can be when bullet deformation is present.
Patterns of Striae on Bullets
 
 
A system has also been described for identification of jacketed sporting rifle bullets using twelve parameters:
1.	Identification number 
2.	Manufacturer 
3.	Weight 
4.	Diameter 
5.	Cartridge 
6.	Base design 
7.	Length of bearing surface 
8.	Color 
9.	Shape 
10.	Location and description of crimping cannelure 
11.	Location and description of other cannelures 
12.	Miscellaneous notes. 
Such parameters may aid in narrowing the search for suspected weapons or ammunition. (Booker, 1980)
There are three results of comparison identification. Test fired and recovered bullets can: (1) be related to the same weapon; (2) be unrelated to the same weapon; (3) not be compared with this type of examination. Conclusions should not be based upon probabilities in test firing.
In many situations, however, the hospital pathologist as medical examiner will not be involved with test firing. The hospital pathology department may receive bullets or bullet fragments from patients. Such evidence should be clearly identified, with a "chain of custody" followed. The pathologist will dictate a report and release the evidence back to the authorities
</p>
<h2>Gunshot Residue</h2>
<p>In many cases, recovered bullets will be too deformed for comparison studies. A method has been described for differentiation of bullets by spark source mass spectrometry (SSMS). This method makes use of the fact that the "lead" of bullets actually may contain up to 26 common elements, of which 12 can be used for differentiation. One of the commonest of these is antimony (1 to 2%) Unfortunately, the study also found that bullets within a box or lot do not have uniform composition, but there may be two or three distinct groups of bullets within a box. Such a study may have limited usefulness in some cases. (Haney and Gallagher, 1975)
When analysis of the bullet lead is necessary, but a copper jacket is present, the copper may be most efficiently removed, without contamination of the lead, by use of concentrated nitric acid. (Izak-Biran et al, 1980)
Detection of the type of bullet (jacketed or not) may be done by a dithiooxamide (rubeanic acid) test. This test detects copper and nickel, which may be components of jacketed ammunition, on the target. The rubeanic acid forms a dark green precipitate in the presence of copper, pink or blue with nickel, and brown with cobalt. Blood and other materials on the target produced false negatives. (Lekstrom and Koons, 1986)
Bullet particles may also be detected in bone fragments from skeletal remains when no soft tissues remain. After determining that radiopaque particles are present, surfaces of the bone fragments containing the particles can be exposed by cutting. The surfaces can then be analyzed by SEM-EDA and by electron probe microanalysis to identify lead (Pb) and antimony (Sb). The electron probe technique aids in differentiating antimony from abundant calcium of bone. (Simmelink et al, 1981) Detection of bullet lead has also been carried out with proton-induced X-ray emission (PIXE) analysis, even in a victim buried for several years (Fischbeck et al, 1986).
Even if an exit wound is present, a search for bullet fragments or jacket material should be done, with radiographs if necessary. A new type of ammunition, Winchester Western Silvertip, may pose a problem, as its aluminum jacket is only faintly radiopaque (Conradi, 1982).
</p>
<h2>Other Injuries & Home Defense</h2>
<p>
Examination of Gunshot Residue
Composition of gunshot residue
Firing a weapon produces combustion of the primer and powder of the cartridge. The residue of the combustion products, or unburned primer or powder components, can be used to detect a fired cartridge. Residue may be found on the skin or clothing of the person who fired the gun, on an entrance wound of a victim, or on other target materials at the scene. The discharge of a firearm, particularly a revolver, can deposit residues even to persons at close proximity, so interpretations as to who fired the weapon should be made with caution. (Thornton, 1986)
The major primer elements are lead (Pb), barium (Ba), or antimony (Sb). Usually, all three are present. Less common elements include aluminum (Al), sulfur (S), tin (Sn), calcium (Ca), potassium (K), chlorine (Cl), or silicon (Si). A mercury-fulminant based primer may be found in ammunition manufactured in Eastern Europe and used in the Middle East.(Zeichner, et al, 1992) Primer elements may be easier to detect in residues because they do not get as hot as the powder, and compounds (not just elements) may be detectable. (Tassa et al, 1982b)
In addition, primer residues may adhere to fired bullets and gradually ablate through the path of the bullet. Thus, primer residue may be found in targets or wounds at considerable distance from the muzzle (up to 200 meters).
The cartridge case, bullet, bullet coating, and metal jacket also contain specific elements that can be detected. Virtually all cartridge cases are made of brass (70% copper and 30% zinc). A few have a nickel coating. Primer cases are of similar composition (Cu-Zn). Bullet cores are most often lead and antimony, with a very few having a ferrous alloy core. Bullet jackets are usually brass (90% copper with 10% zinc), but some are a ferrous alloy and some are aluminum. Some bullet coatings may also contain nickel. (Ravreby, 1982).
Modern gunpowder, or "smokeless" powder, can contain up to 23 organic compounds (FBI study). Nitrocellulose is virtually always present, along with other compounds containing nitrate or nitrogen. One of these compounds, diphenylamine (used as a stabilizer in the powder), can be detected using reagents containing sulfuric acid. (Maloney et al, 1982) Modern gunpowders are also described as "single-base" when the basic ingredient is nitrocellulose and as "double-base" when there is additionally 1 to 40% nitroglycerine added. Hardy and Chera (1979) describe a method to differentiate them using a mass spectrometer.
In the physical examination of the scene or body for evidence of gunshot residue, it must be remembered that lead residues may mimic gunshot residue. Lead residues may be found up to 30 feet from the muzzle, and are always present on the opposite side of a penetrated target. Such a situation has been reported when an intermediate target (glass) was present. (Messler and Armstrong, 1978)
Though the amount of residue deposited tends to decrease with increasing range of fire, the actual deposits can be highly variable for ranges up to 20 cm.(Brown, Cauchi, et al, 1999)
Detection of Gunshot Residue
The major methods for detection of primer residues are neutron activation analysis (NAA), atomic absorption spectrophotometry (AAS), and scanning electron microscopy with energy dispersive analysis (SEM-EDA). For these methods, samples must be obtained from the skin surfaces of a victim at the scene. Delay in obtaining residues, movement, or washing of the body prior to autopsy will diminish or destroy gunshot residues. (Kilty, 1975)
Scanning electron microscopy with energy dispersive analysis (SEM-EDA) has become an excellent method for detection of gunshot residue. (Andrasko and Maehly, 1977)
The method of collection for residue is quite simple and easily carried out in the field (Tassa, et al, 1982a) directly onto the gummed surface of a chuck, or holder, applied to the surface (skin or other material) to be tested. The chuck, with the residue on the surface, can be directly prepared for examination in the SEM device. A polyvinyl-alcohol (PVAL) collection method has been developed that has the advantage of preserving the topical distribution of gunshot residues as well as sampling of other trace materials such as blood.(Schyma and Placidi, 2000)
A major advantage of this method is that SEM can reveal the actual surface details of the particles examined, for comparison with known examples of gunshot residue, and pictures can be taken. The large particles of partially burned powder and the spheres of residue can be distinguished from contaminant materials.




Scanning Electron Micrograph of GSR
 
An X-ray analyzer can be beamed directly onto the particles, so that the energy dispersive pattern (EDX) can be generated, giving the elemental composition of the particles. (Nesbitt et al, 1976) A computer program to speed up the search for GSR particles by SEM has been described (Tillman, 1987)
Diagram of the SEM-EDX pattern of GSR
 
It should be remembered that any hand or body part that was close to the fired weapon may have residue appearing consistent with having fired the weapon (Thornton, 1986). Clothing should always be retained on the body up to autopsy, as this may modify entrance wounds, need examination for gunshot residues, or aid in interpretation of the scene.
Gunshot residue analysis requires careful evaluation. False positives may be caused by contamination or transfer of GSR to the body by mishandling, or when the body is heavily contaminated by GSR from previous shooting. False negatives result from washing of the hands (when this area is sampled) or by victim wearing gloves. A rifle or shotgun may not deposit GSR on hands.
SEM may also have usefulness for examination of bullets, as embedded materials from the target such as bone fragments may aid in reconstruction of the scene (DiMaio VJ et al, 1987). SEM has been used to study tool marks made by the firing pin impressions in the primers of spent cartridges. Such findings could be useful to determine which gun was used to fire the cartridge. Grove et al (1972) found that SEM could reveal clearly all surface detail in the impression and that 50% of shotgun impressions and 75% of rifle impressions could be positively identified on the basis of four or more individual characteristics, given similar class characteristics.
It may be difficult to both find and determine the nature of gunshot wounds in a decomposed body. Determination of the range may be particularly difficult. Extreme care should be taken to avoid misinterpretation of the wounds and artefacts.
Other Examinations
Sometimes the question of whether the victim was holding the firearm arises in investigation. Lee (1986) has described an improved method for the detection of iron traces on the hands by use of a ferrozine spray. Prior to this, a hydroxyguinoline test was employed, but required fluorescent photography. (Stevens and Messler, 1974)
Cases have been described in which suicide victims' hands were stained orange-brown from contact with gun barrels following death, presumably from perspiration coupled with a prolonged post-mortem interval of contact. (Norton et al, 1979)
Latent fingerprints may be detectable on cartridges and expended shell casings. Such fingerprints, called latent because they are transferred via a substance on the skin ridges to an object. On a gun, such substances could include cleaning solvents or gun oils. Usually, the substances consist of perspiration mixed with oils from sebaceous glands. Conditions of increased temperature and low humidity decrease the persistence of fingerprints. Brass retains the fingerprints better than nickel-plated materials. (Given, 1976)
Each firearm sold (other than black powder weapons) has a manufacturer's serial number stamped into it which may be used to identify the weapon. Registration of firearms provides a way of tracing gun ownership. However, attempts may be made to obliterate registration numbers by grinding or filing the metal. (Polk and Giessen, 1975)
Gas chromatography has been used to identify gun oils in targets, and was very sensitive, even with stored specimens (Kijewski and Jakel, 1986).

Other Issues and Forms of Injury
Home Defense
Much is written in the popular literature concerning weapons for home defense, with articles recommending virtually any type of firearm short of a howitzer! Unfortunately, presence of guns in the home leads to more accidents and fatalities (often children) than to actual use in defensive situations. (Kellerman and Reay, 1986).
It should be remembered that most projectiles above .22 cal can penetrate the relatively thin wallboard of houses and apartments, and bullets fired from a military-style rifle might well penetrate through several houses! Perhaps the best weapon, if one were to pick an ideal based upon safety and ability to hit a target under duress, would be a short-barreled shotgun with shells containing small pellets (#6 or 7). (Zaleski, 1982) 
Other Injuries
Persons engaged in target shooting, particularly at indoor firing ranges, are exposed to lead and may develop intoxication with lead (Chau et al, 1995). One study showed half of those tested to have blood lead levels >40 micrograms/dl. Lead levels at firing ranges may be five times that of OSHA standards. (Fischbein et al, 1979) Lead poisoning from retained bullets has been reported, but is most likely with multiple fragments or pellets within one month of injury. One to five years after injury, there is little risk for lead poisoning (Manton and Thal, 1986) Brachial plexus injuries have been reported from firearm recoil. (Wanamaker, 1974) Eye protection (glasses or goggles) should be worn when target shooting to prevent eye injury from ammunition fragments (Heimann and Lemmen, 1986).
Plastic bullets, replacing rubber bullets (implicated in three deaths) used as "safe" projectiles for riot control, were shown in one study to be associated with 13 deaths (seven children) by serious head injury, usually when fired at distances less than the 25 yard range considered be "safe" (Metress and Metress, 1987)
Gun Shot-Entry Wound Mouth.
 

Gun shot Wound-Eye Brow


 

Multiple Gun Shot Wounds

 





Shot Gun Wounds

 


AUTOPSY:
(a) Clothing: Remove clothing layer by layer. Avoid cutting or mutilating a wound pattern on clothing. List them all and note their condition and the extent of blood staining. Record the number and position of bullet holes. It is sufficient to describe the number of bullet holes in the outer garment and adding that bullet holes in the remaining clothes correspond in location to the outer garment. The location of bullet holes in clothes, should be described in relation to the distance from collar, seams, pockets, heel level, etc. A single bullet may produce several holes due to the presence of creases in the garment and simulate more than one shot. Air dry clothes if wet. The size of the bullet hole and the extent of soot and powder distribution should be measured and the density of powder stippling noted. Note whether the fibres of the clothing are turned inwards or outwards. Clothing may be forced into the tissues in shot gun wounds.
Number all entrance and exit wounds. The clothes should be preserved carefully in clean brown paper or plastic bags and sent to the laboratory. Photographs of all layers of clothing should be taken with a scale placed nearby. Probes, fingers, etc, should not be introduced through the defects in the clothing as the direction or distribution of fibres will be changed.
(b) Bullet wounds: Do not wash or cleanse the body until samples have been taken for examination for powder residues. Protect the hands with plastic bags.
Shot Gun Wounds:
(a) The exact location of each wound should be noted in relation to its distance from: (i) the top of the head or the sole of the foot. (ii) midline of the body, and (iii) a fixed anatomical landmark.
(b) The character of the perforation, its shape (stellate, round, slit-like or jagged) and size should be noted and also presence or absence of fouling and stippling.
Take photographs of the wounds including a scale.
(d) Describe the number and distribution of stellite skin perforations caused by individual pellets and the presence or absence of wad injuries.
Measure the total vertical and horizontal spread of the skin wound pattern when satellite perforations are present.
Remove as many pellets as possible. X-ray is helpful in locating the pellets.
(g) Recover wads which reveal the bore of the shot gun and may also have a manufacture’s mark.
Rifled Fire-Arm Wounds:
(a) Note the exact location of each wound.
(b) The character of the perforation, its shape and size should be noted.
Note and measure the abrasion collar, etc. and the powder pattern surrounding the borders of the entrance wound. Difference in the width of the abrasion collar at different points should be noted.
(d) A scaled photograph or a diagram showing the numbered wounds is useful.
If the entrance wound is soiled with blood it should be sponged carefully to know tattooing,
(e) Track Taken by the Bullet through the body:
Bullet tracks should be numbered and described individually. It is advisable to record the wound in the skin and the wound track through the body in one section.
Probes should not be introduced through the track.
The path taken by the bullet through the body should be carefully traced by dissection. Measure the height of both entrance and exit wounds from the under surface of the heel.
Describe all organs and tissues through which the bullet passes and note the size of the defect or lacerations produced; include specific vessels injured and note the quantity and location of internal haemorrhage; note secondary missiles related to fracture of bone.
If there are multiple tracks, each should be followed from the point of entrance to exit.
f) Remove the bullet with bare fingers or a forceps protected with rubber tubing may be used.
Describe characteristics of the exit wound.
(D) Microscopic Examination: (1) Prepare sections from wounds of entry to demonstrate injury and powder residues. (2) Prepare sections from depth of wound to determine powder residues.
(E) Special Procedures: (1) Photography of wounds. (2) X-ray examination: (a) to locate bullets and shots, (b) to locate fragments of metal and bone, (c) to show course and direction of missiles. (3) Chemical examination: (a) for powder residues. (b) Neutron activation analysis for residues from primer (c) Detection of trace metals.
(F) Specimens to save: (1) The skin around the entrance and exit wounds should be cut out including at least 2.5 cm. of the skin around and 5 mm. beneath the wound and preserved in rectified spirit. (2) Blood for typing. (3) Viscera for chemical analysis.
G. PRESERVATION, MARKING AND PACKING OF EXHIBITS:
Fire arms: Identifying initials should be scribed on to the gun’s frame, receiver, or slide and on the barrel.
Fired cartridge cases: The marks should be scratched on the inside of the open end. They may be wrapped in cotton and packed in cardboard boxes.
Fired bullets: The marks should be scratched on the base, wrapped in cotton and packed in cardboard boxes. Each bullet should be packed separately.
Pellets, slugs, wads, etc: They may be packed in cardboard box wrapped in cotton after drying and the container labeled.
Clothes: The area of the powder tattooing should be preserved by fastening a cellophane paper over it and packed in a box.
CIRCUMSTANCES OF DEATH:
(1) Suicide: The sites of election are: (i) temple (ii) centre of forehead, (iii) roof of mouth, (iv) Midline behind the chin, and (v) left side of front of chest. The wound is usually of contact type. A close up or distant shot is rarely suicidal. Suicides usually pull the clothes aside to bare the skin before shooting themselves. The wound is usually single but rarely multiple suicidal wounds are seen involving a single region, e.g. temple, chest or abdomen. In such cases, the first shot does not incapacitate the victim immediately. The weapon is usually found at the hands due to cadaveric spasm. There is usually a motive and he may leave a note. Suicide by firearm is seen mostly in males.
(2) Homicide: A great variety of wounds can occur depending upon the circumstances. A close up or distant shot is usually seen. The wounds may be multiple and may be found on the back or sides of the body, or involve different regions of the body. The weapon will not be found at the scene. There may be evidence of struggle.
(3) Accident: They are rare and usually single. The wounds are found on the front of the body and frequently directed upwards.
Precautions:
Preserve clothing: a) for correlation with wounds upon the body and (b) to determine entrance and exit wounds.
Recover projectiles and fragments of bullets to determine caliber and identity of the weapon.
Remember that projectiles may undergo internal ricochet after striking bone, especially in the skull.
Remember that projectiles may enter blood vessels or spinal canal and transported to unexpected parts of the body.
Caliber of the bullet cannot be predicted by the size of the entrance wound.
Do not cause distortion of projectiles by careless dissection.
GUN SHOT WOUNDS
Preservation and collection of evidence at the scene of death.
Identification of the weapon
Discovery of the wounds and identification of gunshot wounds.
Number and location of wounds in the clothing and on the body
Feature of gunshot wounds and adjacent areas
Range of fire
Angle of fire
Number of shots fire
Cause of projectile in the body
Retrieval of the bullet or pellets and determination of the type of gun.
Retrieval of foreign material (fabric, wadding and so on) from wound tract.
Period of survival
Identification’s of lethal injury
Record of injuries for presentation in court (repu)
Special investigation (Finger Print, blood type, toxicology),




EXAMINATION OF THE SCENE
Study of the circumstances of shooting
Preservation of evidence (Finger Print on the weapon, gunpowder on hands)
Examination of the gun and the body, and recording of findings.
Collection of evidence (gun empty cartridges, shells, clothing, blood steam hair)
Preliminary advice on the live of further investigation.
Firearm Injuries
Scene
Besides taking the usual precautions at the scene with regard to the preservation of fingerprints and the position of the body, until the preliminary police examinations have been completed, special caution must be exercised both as regard to handling the weapon or to ensure that it is not touched by anyone. If the missile is found embedded in wood or some similar material, it should not be extracted, but if its examination proves necessary it should be cutout together with material in which it is embedded. Under no circumstances should it be gripped in metal forceps, to avoid any damage before being taken to the laboratory. The same principle applied to cartridge cases found at the scene. Any marks made subsequently upon the missile or cartridge case may make it difficult or impossible for the ballistics experts to match them with particular weapon. If the weapon is at the scene of shooting, its position in relation to the decreased must be noted. It must be borne in mind that even after serious injury, the deceased may be capable of some movement or locomotion before death occurs. The investigating person should keep following points in mind

Study the circumstances of the firing
•	Location of shooting 
•	Presence or absence of gun 
•	Type of gun 
•	Personal history of victim 
•	Conversation with the witness
Preservation of evidence
•	Finger prints on door knobs, weapon, wire glasses tape 
•	Photographs of scene/video-graphy of scene. 
•	Pick up weapon from muzzle with gloved hands 
•	Proper handling of cloth and body 
•	Type of bullets or shells.
Recording of Findings 
•	Notes of details of circumstances of death + observation made with photograph. 
•	General appearance of the location of death. 
•	If gun into position in relation to the body should be noted as well as its serial number, make model caliber, type of action and adscription of the ammunition. 
•	Observation on the number of gunshot wounds. Position in the cloths and on body. Notes on positive of boning, tattooing of powder on clothing and wounds of the body.
Collection of evidence 
•	Gun 
•	Empty cartridge/bullet, shells, clothing 
•	Blood stains, hairs
If extended in wall, ceiling or furniture it should be extracted and retained.Bullets put in cardboard boxes, not in metal containers. 
The type of bullets and their makings may help identify the gun.
Shells collected in absence of gun- help identify gun.
Preliminary advice on the line of further investigation
•	Medical man with wound ballistic training is the best person to interpret wounds on the body
Artifacts in hospital 
•	Surgical intervention 
•	Trochar wounds 
•	Increase in size in decomposed bodies 
•	Old bullets in body
At the scene, consideration should be given to the presence or absence of weapon, and its position in relation to the body, position of blood stains, signs of disturbance, accessibility to the scene (e.g. how the door was secured from the inside), position of spent cartridge cases, trajectory of missiles, and impact marks on object or surfaces from missiles and their distribution.
The site of the wound in most suicide cases conforms to well recognized selected areas such as temple, mouth, and midline structures to the front of the body. The direction of the wound track from site is a further good indication of the aim of the shooter towards a particular vital structure such as heart or brain,.
The range of discharge of the firearm is another useful factor, which may help confirm on manner of death as being self-inflicted. Unless there is some mechanism to discharge a firearm from a distance further than arm is reach, than such a discharge is extremely unlikely to have been self-inflicted.
INJURIES BY EXPLOSIVES
The recent upsurge of terrorism for political and other purposes in many parts of the world has brought with it the use of explosives. It seems that in the general political unrest, which is prevalent in the world, the bomb will continue to be used to reinforce direct and indirect political objectives and therefore, a medico-legal expert needs to be conversant with some basic knowledge about the effects contributing towards injuries/death etc. Identification of the material used in the manufacture of the bomb and mechanism of its explosion, etc. are the domains of the forensic scientists.
Most of our knowledge of explosions has been gained through wartime events. There have also been some notable explosions affecting civilians such as the one in Texas City in 1947 when a ship loaded with ammunition exploded at the docks killing about 560 people and injuring over 3000.
Following an explosion, a person can be injured/killed in a number of ways:
If he is quite near the explosion, he can be blown to pieces.
He can be injured by a wave of pressure, called the ‘shock wave’, which spreads concentrically from the seat of the explosion. When the explosion is in air, the pressure wave is referred to as air-blast.
He can sustain ‘flash burns’ from the momentary heat radiation or, if his clothing or other material is set on fire, he can sustain ordinary burns.
He can be struck by ‘flying missiles’ propelled by the explosion.
He can be injured or crushed by debris, usually of building(s) demolished by the explosion.
He can be overcome by fumes generated as a result of the explosion.
The above factor(s) may operate solely or in varying combinations and the relative importance of each will depend upon the tye of detonation, the distance of the victim from the seat of explosion and the location of the explosion. Each factor is being discussed.
Disruptive Effects: If the victim is almost in contact with a large bomb (usually when he is carrying it or sitting with it in some vehicle), he may be blown to pieces.. a pre-mature explosion, sometimes during the act of setting the timer, may cause disruptive injuries. With smaller explosions or when the victim is a few feet away, disruption is limited to the blowing off of head or lib or the mangling of a localized area. therefore, sometimes a part of the body may be totally destroyed while the remainder of the victim being remarkably intact. The pieces can get scattered over an area of 100 metres or more from the seat of explosion. Many parts of the body may never be found having mixed with the masonry and other debris of the bomb-site.
Air Blast (Shock Wave): A blast comprises a wave of compression, which spreads concentrically from the blast-centre. The velocity of the shock wave depends upon the distance from the epicenter, being many times the speed of sound in the air at the start but rapidly decreases as it spreads out. This wave of compression/high pressure is followed by a week wave of negative pressure (below atmospheric), so that a rapid double change in pressure is suffered by the victim. The magnitude of the blast varies with the energy released and also with the distance from the epicenter. As the distance from the explosion increases, the peak pressure falls rapidly, almost exponentially. About 100 lb/sq. inch (690kPa) is the minimum threshold for producing serious damage to human beings.
Effects of Blast Wave/Shock Wave: The high pressure shock wave generated by an explosion can knock a person down and thus cause injury but the specific injury associated with blast is due to the shock wave being propagated through the body. It causes most damage at an interface between tissues in contact with the atmosphere and that is why the lung is usually the worst sufferer. The shock wave can pass through solid homogenous tissues like muscle and liver, causing little or no damage but in the lungs the damage is caused owing to marked variation in density between the alveolar walls and the contained air so that damping of shock wave occurs leading to disruptive effects. Its transit through the lungs can tear the alveolar septa and give rise to alveolar haemorrhage. Other findings in the lungs may include sub pleural patchy haemorrhages (often in the line of ribs) and intra-pulmonary haemorrhages. The air passages may be filled with bloody froth causing airway obstruction and hypoxia in addition to the primary damage. Later, neutrophilic reaction may develop around the haemorrhagic areas and those can progress onto brocho-pneumonia. The pulmonary injury is a specific injury of the air-blast and is sometimes called as ‘blast lung’. However, the lungs can also be bruised by direct blows on the chest and haemorrhagic areas can arise by aspiration of blood or regurgitation of stomach contents down the trachea. Rarely, when the victim dies soon after the explosion of a bomb, this finding may not be seen, presumably due to relatively small amount of explosive detonated and the victim being somewhat away from the seat of explosion so that the blast wave is unable to exert any serious effect.
Blast may also cause damage to the ears. Its effects tend to be capricious because the pressure on the tympanic membrane is modified by many factors but when the pressure rises excessively above the atmospheric, rupture is likely.
Gastrointestinal system often suffers from the effects of a blast because like the lung, it contains air and gases and is thus not a uniform medium for the transit of shock wave. The caecum and colon are more often hurt than the ileum, jejunum and stomach, presumably because they are larger and often contain more gases. Occasionally, ruptures of the gut can occur if the blast is violent and the victim is situated nearby.
Burns: When a bomb explodes, the temperature of explosive gases can exceed 2000oC and the heat radiated momentarily can cause ‘flash burns’. The amount of thermal radiation received decreases with the square of the distance from the explosion and the intensity of explosion
The principal feature of stabbed wound is their depth which is usually greater than their width. Although stabbed wounds are usually associated with knives and daggers, any piercing instrument such as scissors, screwdriver or a pointed stick may be used. The external wound gives no indication of its depth. Even with massive internal hemorrhage there may be no bleeding from the external wound. The edges of wound may give some indication of the nature of the instrument. Majority of cases are homicidal in nature and more rarely suicidal. The cases of accidental stabbing have occurred but are rare.

</p>


  </div>
</section>

<?php include 'footer.php'; ?>